const CREATE = "CREATE";
const READ_POSTS = "READ_POSTS";
const READ_SEARCH_POSTS = "READ_SEARCH_POSTS";
const READ_POST = "READ_POST";
const UPDATE = "UPDATE";
const DELETE = "DELETE";
const LOGIN = "LOGIN";
const LOGOUT = "LOGOUT";
const START_LOADING = "START_LOADING";
const END_LOADING = "END_LOADING";
const DARK_MODE_TOGGLE = "DARK_MODE_TOGGLE";

export {
  CREATE,
  READ_POSTS,
  READ_SEARCH_POSTS,
  READ_POST,
  UPDATE,
  DELETE,
  LOGIN,
  LOGOUT,
  START_LOADING,
  END_LOADING,
  DARK_MODE_TOGGLE,
};
